// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqUI6n477mi7tFpjDdzXGs0BS9DgCRuBQ',
    appId: '1:880732641241:web:de0ae6bd97c69dee98ebc8',
    messagingSenderId: '880732641241',
    projectId: 'hris-eb863',
    authDomain: 'hris-eb863.firebaseapp.com',
    storageBucket: 'hris-eb863.firebasestorage.app',
    measurementId: 'G-MHHZXDRTH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyART0OUU_8Y35KCjJXZwc3DO6CzyreKP4A',
    appId: '1:880732641241:android:0d5de2443bec185398ebc8',
    messagingSenderId: '880732641241',
    projectId: 'hris-eb863',
    storageBucket: 'hris-eb863.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBaQA7Y2pe7juoU8qSNozXp8W95wkJgqY',
    appId: '1:880732641241:ios:841626a105a4a7cd98ebc8',
    messagingSenderId: '880732641241',
    projectId: 'hris-eb863',
    storageBucket: 'hris-eb863.firebasestorage.app',
    iosBundleId: 'com.hrispentamoo',
  );
}
